-- QR Code Generator (apps/qr) Schema
-- Created: 2026-07-23

CREATE TABLE IF NOT EXISTS qr_links (
  id SERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  edit_token TEXT UNIQUE NOT NULL,
  target_url TEXT NOT NULL,
  label TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS qr_scans (
  id SERIAL PRIMARY KEY,
  qr_link_id INTEGER NOT NULL REFERENCES qr_links(id) ON DELETE CASCADE,
  scanned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  user_agent TEXT,
  referrer TEXT
);
